### ISSUE TITLE
Error in the backend user management module

### ISSUE THREAD

**Issue by stephangrass** [Gernott/mask#602] opened 2023-11-02 06:22 UTC
When activating and deactivating users in the backend user module, I receive the following error:

Core: Error handler (BE): PHP Warning: Undefined array key "tree" in /.../typo3/vendor/mask/mask/Classes/ExpressionLanguage/MaskFunctionsProvider.php line 48 

Core: Error handler (BE): PHP Warning: Attempt to read property "rootLine" on null in /.../typo3/vendor/mask/mask/Classes/ExpressionLanguage/MaskFunctionsProvider.php line 48 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: ksort(): Argument #1 ($array) must be of type array, null given | TypeError thrown in file /.../typo3/vendor/mask/mask/Classes/ExpressionLanguage/MaskFunctionsProvider.php in line 52. Requested URL: https://.../typo3/record/commit?token=--AnonymizedToken--&data%5Bbe_users%5D%5B24%5D%5Bdisable%5D=0&redirect=/typo3/module/backend/user/management?token%3D--AnonymizedToken-- 

I#m using TYPO3 12.4.7 and Mask 8.3.5, Composer Installation

**Comment by nhovratov** [comment] 2023-11-02 07:21
This is already fixed in Mask 8.3.6. Please update to the latest version.

**Comment by stephangrass** [comment] 2023-11-02 07:29
Ah, sorry ...

**Closed** 2023-11-02 07:40 UTC

**Comment by nhovratov** [comment] 2023-11-02 07:42
Duplicate of https://github.com/Gernott/mask/issues/599
