### ISSUE TITLE
Missing labels after "saving and add new"

### ISSUE THREAD

**Issue by webdev2027** [Gernott/mask#166] opened 2018-08-14 11:22 UTC
Hi, I'm working with `TYPO3 8.7.18` `PHP 7.0` and `mask 3.3.1`.
After editing a new mask element and clicking "save and add new" (speichern und neue erstellen) the first time, everything ist fine.
![unbenannt13](https://user-images.githubusercontent.com/5501876/44088794-c082759e-9fc4-11e8-804a-eb1977aea8be.png)

![unbenannt-2](https://user-images.githubusercontent.com/5501876/44088755-9f69a90e-9fc4-11e8-9ae1-2b389380f1a5.png)

-
Adding the 2nd, 3rd, 4th, ... Element with the same procedure (save and add new) the labels from the TCA-Fields are missing.
![unbenannt-4](https://user-images.githubusercontent.com/5501876/44088588-0746b72a-9fc4-11e8-8a11-1577d074e8fe.png)

That's not a big issue, but I'm just wondering how this behaviour can be?!

**Comment by butu** [comment] 2018-09-17 15:14
duplicate of #124

**Closed by butu** 2018-09-17 15:14 UTC
Labels: duplicate
