### ISSUE TITLE
Order of IRRE elements gets lost in translations

### ISSUE THREAD

**Issue by sgalinskiWagner** [Gernott/mask#367] opened 2020-10-14 18:44 UTC
I have a multilanguage setup and use a Mask element with repeating elements inside it. 
After adding a new repeating element to the base element and moving it to the desired position, I need it in the translation as well.
There I click on the "Localize" button. The new translation is then added to the end of the list of the IRRE elements, not where the corresponding element in the default language is.

Tested with Mask 6.0.1 in TYPO3 10.4.9.

**Comment by nhovratov** [comment] 2020-10-14 19:18
Hi @sgalinskiWagner ,

first of all: i can reproduce this. But i have a hunch that this is a core issue, since mask has nothing to do with translating CE.

Will look into it deeper when I have time. Thanks for the report!

**Comment by nhovratov** [comment] 2020-10-14 19:40
Can you try the new option allowLanguageSynchronization with "value of default language" ? This seems to work well and you can still override the value. The records are kept in sync, so if you add or delete a record in default language, this will automatically be updated in the translations.
Maybe we can change this to the default behaviour?

**Comment by sgalinskiWagner** [comment] 2020-10-15 13:41
This does work but it feels odd to me that these elements are still editable if they are supposed to be the same as the default language. In other places like input elements, allowLanguageSynchronization disables editing the elements entirely.

**Comment by nhovratov** [comment] 2020-10-15 16:01
Seems there is still room for improvement on TYPO3 side. I will close this here but feel free to open the same issue on forge.

**Closed by nhovratov** 2020-10-15 16:01 UTC
