### ISSUE TITLE
MASK 4 with TYPO3 9 sorts entries in "Repeating" by their keys after saving.

### ISSUE THREAD

**Issue by kevin-appelt** [Gernott/mask#188] opened 2018-10-20 11:59 UTC
If I use a repeating element and create the fields with the keys `header`,`bodytext` and `image` (in this order) in it, and click the save button, the fields are displayed in the order `bodytext`,`header` and `image` after saving.

**Comment by butu** [comment] 2018-10-22 12:51
This should already be fixed on current master :)

**Comment by kevin-appelt** [comment] 2018-10-30 08:57
Ah, great. 
Is there any information when the bugfix release is planned? The bug is a little annoying and I would like to prevent mask from being required as dev-master. ;)

**Comment by brandung-sjorek** [comment] 2018-10-31 11:31
This bug applies to EXT:mask version ≥ 3.3.2, including 4.x and master. It is not fixed yet.

The sorting of json is generally a good idea, ie. to reduce merge conflicts. The current implementation breaks mask-content-elements using repeatables. If you edit and save a mask-content-element (no matter which) all objects (not arrays) are sorted by key in the whole json-file. This happens in `\MASK\Mask\Domain\Repository\StorageRepository::sortJson()`. This method is sorts the whole json recursivly since mask version 3.3.2. 

*What is broken:* For repeatables the `$TCA[…][types][…][showitems]`-entry is generated by the order of the “tca”-object-keys in the mask-json. Hence sorting the json for this special case breaks the visual appearance of mask-elements with repeatables.

*As long as the is no patch available, we recommend not to edit any mask-elements.* We're currently preparing a PR for EXT:mask 3.x and EXT:mask 4.x to prevent the sorting for repeatables.

If you already have updated your json with any of the mentioned mask-versions, there is no other option for you as to manually revert your json, either in your VCS or by other means. Editing all your mask-elements and sorting the fields back into the desired order, won't work without a patch.

**Comment by markuspoerschke** [comment] 2018-11-14 08:47
Looks like the defect was introduced in 3d0cdbc5bb06a97832f3ce02722b2e4b51327f91. The sorting of the `mask.json` is done to get an deterministic output of the data. Since „[a]n object is an unordered set of name/value pairs“ (json.org) only arrays were sorted. For the "tca" fields in the JSON file the characteristic of PHP is used that hash tables (aka arrays in PHP) can be sorted by their key.

I provided a fix that skips sorting the keys of the "tca" fields.

#195

**Comment by faltrock-abone** [comment] 2018-11-28 12:00
This was indeed fixed by #181 already, which is only in `dev-master` and not 4.0.0. I just reproduced the bug with v4.0.0 and "fixed" it by upgrading to `dev-master`. (Well, plus going into the mask element and re-arranging the fields and updating the JSON, installing a different version of mask does nothing in itself of course.)

**Closed** 2020-09-23 08:13 UTC
