### ISSUE TITLE
Field duplication by changing sorting when repeating element in repeating element

### ISSUE THREAD

**Issue by marcelmarty** [Gernott/mask#531] opened 2022-12-13 09:44 UTC
Used Versions:
- mask 8.0.5
- TYPO3 11.5.5 (the problem occurs in TYPO3 11.5.19 too)

Steps to reproduce:
1. Create a repeating element, let's name it "Categories".
2. Create a repeating element within "Categories", name it "Subcategories".
3. Create an RTE field within Subcategories,  let's name it "Description".
4. Go to a page and add the created content element
5. Add 4-5 Subcategories with complete descriptions (Test 1 until Test 5) and save the content element
7. Open the content element again and create a new subcategory below the previous created subcategories and move it's location up 4 positions (with the arrows which change the sorting). 
8. With each position the new subcategory has moved up, the field "Description" has been duplicated (multiple fields among themselves)

![image](https://user-images.githubusercontent.com/1627210/207282653-0e7669c8-3333-40b6-9173-09a3ecc9b9c0.png)

This will result in an (invisible) error when the content element has been saved, and the added field text will be removed. If the content element will be edited again, the text of the field is gone.

**Comment by nhovratov** [comment] 2022-12-13 09:51
Hey @marcelmarty , thanks for the report. This looks like a TYPO3 core bug. Does this happen on the latest 11.5.19 version of TYPO3?

**Comment by marcelmarty** [comment] 2022-12-13 09:55
@nhovratov Don't know... Give me some minutes to update to the latest TYPO3 11.5.19. I'll let you know the result.

**Comment by marcelmarty** [comment] 2022-12-13 10:04
@nhovratov Unfortunately, the problem still exists after upgrading to TYPO3 11.5.19.

**Comment by nhovratov** [comment] 2022-12-13 13:25
Thanks for testing. I will try to reproduce it and probably create a forge ticket from this.

**Comment by marcelmarty** [comment] 2022-12-22 06:58
@nhovratov Do you have any updates on this? I don't want to stress you, it's just because of the customer is awaiting a solution from our side, and we cannot provide...  ;-)

**Comment by nhovratov** [comment] 2022-12-22 09:42
@marcelmarty I haven't gotten into it yet. If you want to speed things up, create a TYPO3 forge ticket, as it is 100% a TYPO3 issue. Then there will be more people than me, wo can read the issue and provide a fix. If you need a fix right away, you should pay someone. Even then, you will have to wait until a new official release. Or you patch the core with composer for the time.

**Comment by marcelmarty** [comment] 2022-12-22 09:55
@nhovratov Created forge here: https://forge.typo3.org/issues/99410

**Comment by nhovratov** [comment] 2022-12-22 10:04
Thanks, I will close this one then.

**Closed by nhovratov** 2022-12-22 10:04 UTC
