### ISSUE TITLE
Icon Field empty after "Flush all Caches"

### ISSUE THREAD

**Issue by thomas-niederberger** [Gernott/mask#393] opened 2021-03-24 15:54 UTC
I run the TYPO3 10.4.14 and Mask 6.6.1. At the moment I "Flush all Caches" the Icon field becomes empty after I try to edit a Mask element. When I close the Mask element and reopen it again, the icon field is back on.

**Comment by nhovratov** [comment] 2021-03-24 18:45
Hi @thomas-niederberger Thomas,

does this happen every time? I can't reproduce this. The icon is visible at all times.

**Comment by nhovratov** [comment] 2021-05-13 11:17
Should be fixed with v7.

**Closed by nhovratov** 2021-05-13 11:17 UTC
