### ISSUE TITLE
Content fallback for nested content element aren´t rendered in frontend

### ISSUE THREAD

**Issue by opaque01** [Gernott/mask#184] opened 2018-10-15 11:23 UTC
Hi

Nested content elements are not visible in FE if they are not translated. 

TS:
```
[globalVar = GP:L = 9]
config.sys_language_uid = 9
config.language = en
config.htmlTag_langKey = en-US
config.locale_all = en_US.UTF-8
config.htmlTag_setParams = lang="en-US"
config.sys_language_mode = content_fallback
config.sys_language_overlay = 1
[end]
```

TYPO3: 8.7.15
PHP: 7.0
Mask: 3.3.2

**Comment by Gernott** [comment] 2018-10-15 11:31
Can you give us more details please:
- is the whole element missing, or only the child elements?
- does it work with regular TYPO3 elements (e.g. text/media with media files)?
- does it work with records (e.g. news with relations to links)?
- have you tried other TypoScript configurations?

**Comment by opaque01** [comment] 2018-10-15 11:46
Hi
>     * is the whole element missing, or only the child elements?
No, only the child elements. E.G. {data.header} is visible.
>     * does it work with regular TYPO3 elements (e.g. text/media with media files)?
Yes
>     * does it work with records (e.g. news with relations to links)?
tx_news works
>     * have you tried other TypoScript configurations?
Yes

**Comment by opaque01** [comment] 2018-10-16 19:10
After some test - only nested content elments inside MASK "Repeating" or "Content" are not rendered.

**Comment by butu** [comment] 2018-10-19 12:01
Have you activated all the checkboxes in localization tab except **Show removed localization records
** in **both** the repeating field AND the content field? If yes, did you do that before or after you translated the content elements?

**Comment by opaque01** [comment] 2018-10-19 12:28
I did only translated the pages. The content should fetched from the default language.

**Comment by butu** [comment] 2018-10-19 12:44
Ah! Now i got you! I can reproduce it. This is already a known missing feature. See #158. Content fallback for repeating elements isn't a trivial thing unfortunately, and hasn't been tackled yet.

You can PR a solution or sponsor this new feature :)

I will close this ticket as it is a duplicate of #158

**Closed by butu** 2018-10-19 12:44 UTC
