### ISSUE TITLE
"Create New Button" in repeater element in connected translation mode

### ISSUE THREAD

**Issue by zwenn** [Gernott/mask#423] opened 2021-07-20 07:41 UTC
Hi,

I have got a problem with the translations of repeater elements in typo3 connected translation mode.
[https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizedContent/Index.html]

Default behavior of Typo3 is then not to show "Create new"-Buttons.

I defind two languages in my site configuration: german = 0 and english = 1.

If I translate a repeater element to the english language, inside this element the "Create new"-Buttons are visible and inside further elements in deeper nesting.
<img width="244" alt="create-new-buttons-in-translation" src="https://user-images.githubusercontent.com/6844841/126278033-044a50e1-32dd-4726-ad38-e20f35280d12.png">

In deeper nesting levels creating new elements leads to an Exception:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1438183881: TCA table tt_content ctrl['type'] is set to CType, but this field does not exist in the database of this table | UnexpectedValueException thrown in file /.../typo3_src-10.4.17/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseRecordTypeValue.php in line 62

In my opinion the "Create new"-Buttons should not be visible at all.

Typo3 10.4.17
mask 7.0.15

**Comment by nhovratov** [comment] 2021-07-20 10:22
Hi @zwenn,

I'm not sure if it is correct of TYPO3 to show the "New-Record"-Button in connected mode either.
I have not found a similar issue in forge, so you are free to create a new issue there. Mask can't change this behaviour.
Besides that your error is really strange, as it states your table `tt_content` does not have the field `CType`.
Also with a quick test, I couldn't reproduce the error. I can create new records even in deeper nested fields.

**Comment by nhovratov** [comment] 2021-08-12 16:43
@zwenn 

In TYPO3 v11 there will be a new TCA option for disabling the create new button: https://review.typo3.org/c/Packages/TYPO3.CMS/+/70315/

**Comment by nhovratov** [comment] 2022-03-04 20:52
Closing as it is not strictly related to Mask and a solution was suggested for TYPO3 v11.

**Closed by nhovratov** 2022-03-04 20:52 UTC
