### ISSUE TITLE
Mask + Typo3 v12.3 Backend not showing up

### ISSUE THREAD

**Issue by ByteBandito** [Gernott/mask#546] opened 2023-04-18 08:48 UTC
- Two as far as I can see it identical websites. One v12.2 and one v12.3 ...
- Mask 8.08
- Mask and Fluid Content Elements are includeded in TypoScript

When clicking on "Mask" (points to /typo3/module/mask/) the content stays empty.
No errors shown on screen or log or browser-console.

Any idea for me?

**Comment by liayn** [comment] 2023-04-18 08:49
Duplicate of https://github.com/Gernott/mask/issues/545

**Comment by ByteBandito** [comment] 2023-04-18 09:05
Thank you Liayn, that solved my problem.

But I still dont understand why there were no errors shown in Browser-console....

**Comment by nhovratov** [comment] 2023-04-18 11:20
Thanks, closing this one in favor of #545

**Closed by nhovratov** 2023-04-18 11:20 UTC
