### ISSUE TITLE
Missing element title after adding a backend preview template

### ISSUE THREAD

**Issue by sniepy** [Gernott/mask#316] opened 2020-07-07 08:57 UTC
Hey guys,

after adding a backend preview template to my mask element I ended up missing the element title in t3 backend.

Hope anybody can help me.

**Comment by nhovratov** [comment] 2020-07-07 11:32
This is already fixed on master, will be shipped in the next release.

**Comment by nhovratov** [comment] 2020-07-07 11:41
What version of typo3/mask are you using? Can you provide a screenshot and/or setup, please?

**Comment by sniepy** [comment] 2020-07-07 11:52
> What version of typo3/mask are you using? Can you provide a screenshot and/or setup, please?

I'm using Typo3 10.4.4 and Mask 5.0.0.

<img width="1142" alt="Bildschirmfoto 2020-07-07 um 13 43 44" src="https://user-images.githubusercontent.com/67950933/86776996-f21f1600-c058-11ea-8e24-da5ba661fca5.png">
<img width="773" alt="Bildschirmfoto 2020-07-07 um 13 46 33" src="https://user-images.githubusercontent.com/67950933/86777008-f3e8d980-c058-11ea-8fb5-621711dbc096.png">


If I don't add a backend preview template ist shows the title only as it should.

**Comment by nhovratov** [comment] 2020-07-07 12:26
For me it works. Is it possible that some other extension is overriding the title? Because it looks like the header of mask is not rendered at all. If just the title was missing then there would be more space above the line since there is a `<br>` tag.
Can you scan your site for `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/layout/class.tx_cms_layout.php']['tt_content_drawItem']` and look if some other extension is hooked in?

**Comment by sniepy** [comment] 2020-07-07 14:37
Thanks for your help. I'm not a developer actually, so I hope this is what you meant by scanning:
<img width="603" alt="Bildschirmfoto 2020-07-07 um 16 20 31" src="https://user-images.githubusercontent.com/67950933/86797291-ca877800-c06f-11ea-9ddc-dbac309c6ee4.png">

Actually I'm stepping over from dce to mask right now and I tried deactivating dce and all other extensions.
It didn't work for me.

**Comment by nhovratov** [comment] 2020-07-07 15:31
Ah, ok i had new Fluid Based page layout disabled. Now i can reproduce. Will investigate, thanks!

**Comment by sniepy** [comment] 2020-07-07 15:34
Thank you! Would you let me know if you find a solution?

**Comment by nhovratov** [comment] 2020-07-07 15:50
It looks like it is not possible anymore to set a custom header in the new Fluid Based Page Module, just the content. You can just disable this feature in Settings->Feature Toggles->Fluid Based Page Module until this issue is fixed (there are actually more bugs coming with that). This is a TYPO3 core bug, so mask itself won't provide a fix for that. I will open an issue for that in the TYPO3 issue tracker, thanks for the report!

**Comment by sniepy** [comment] 2020-07-07 15:54
Thank you and welcome! It's a personal site, so it'll do as it is. But I'm looking forward to a fix.

**Comment by nhovratov** [comment] 2020-09-25 08:03
Closing because of TYPO3 bug not mask

**Closed by nhovratov** 2020-09-25 08:03 UTC
